# Generated by Django 4.2.4 on 2023-10-04 19:50

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'posts', 'verbose_name_plural': '03 Posts'},
        ),
        migrations.AlterField(
            model_name='post',
            name='miniature',
            field=models.ImageField(upload_to=posts.models.custom_upload_miniature),
        ),
    ]
