# Generated by Django 4.2.4 on 2025-05-10 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'comments', 'verbose_name_plural': '04 Comentarios'},
        ),
    ]
